In [2]:
#1.The Financial Analyst’s Dilemma 

import numpy as np
stock_prices = np.random.randint(100,501,(30,5))
# avg stock prices
avg_prices = np.mean(stock_prices, axis=0)
rounded_avg = np.round(avg_prices)

#the highest stock price recorded 
highest_price = np.max(stock_prices)
max_index = np.unravel_index(np.argmax(stock_prices),stock_prices.shape)
day,company = max_index
 
#normalized_prices = (stock_price - min_price) / (max_price - min_price)
min_price = np.min(stock_prices)
max_price = np.max(stock_prices)
normalized_prices = (stock_prices - min_price) / (max_price - min_price)
round_val = np.round(normalized_prices,2)

risky_days = {} 
for day in range(stock_prices.shape[0]): 
    prices = stock_prices[day]            
    risky_prices = prices[prices < 200] 
    if risky_prices.size > 0:            
        risky_days[day] = risky_prices.tolist() 

print("Average stock prices: ", rounded_avg)
print(f'Highest price recorded: {highest_price} at Day {day}, Company {company}')
print("normalized_prices: ",round_val)

print("Risky Investment Days:")
for day, prices in risky_days.items():
    print(f"Day {day + 1}: {prices}")

Average stock prices:  [322. 289. 303. 312. 311.]
Highest price recorded: 500 at Day 29, Company 3
normalized_prices:  [[0.99 0.43 0.05 0.2  0.36]
 [0.27 0.54 0.92 0.13 0.2 ]
 [0.2  0.22 0.56 0.97 0.99]
 [0.93 0.08 0.01 0.54 0.24]
 [0.2  0.86 0.64 0.19 0.23]
 [0.88 0.25 0.38 0.55 0.82]
 [0.1  0.84 0.24 0.87 0.07]
 [0.99 0.2  0.19 0.89 0.37]
 [0.94 0.6  0.83 0.43 0.78]
 [0.03 0.22 0.05 0.32 0.78]
 [0.5  0.67 0.96 0.64 0.49]
 [0.83 0.51 0.57 1.   0.05]
 [0.14 0.83 0.09 0.8  0.94]
 [0.79 0.52 0.85 0.36 0.54]
 [0.71 0.66 0.47 0.93 0.94]
 [0.05 0.52 0.49 0.39 0.85]
 [0.71 0.54 0.78 0.11 0.69]
 [0.95 0.14 0.75 0.06 0.15]
 [0.68 0.37 0.81 0.6  0.76]
 [0.7  0.62 0.79 0.17 0.88]
 [0.26 0.57 0.92 0.5  0.  ]
 [0.09 0.21 0.58 0.58 0.94]
 [0.39 0.31 0.44 0.18 0.19]
 [0.66 0.05 0.63 0.38 0.93]
 [0.51 1.   0.14 0.74 0.76]
 [0.8  0.21 0.42 0.51 0.01]
 [0.95 0.79 0.94 0.82 0.76]
 [0.12 0.33 0.31 0.63 0.16]
 [0.97 0.16 0.08 0.22 0.21]
 [0.16 0.81 0.18 1.   0.58]]
Risky Investment Days:
Day 1: [123, 182]

In [11]:
#2. The Space Mission Resource Allocation 

ar = np.array([
    [15, 40, 32],
    [20, 42, 35],
    [25, 38, 30],
    [18, 50, 40],
    [22, 37, 36],
    [28, 45, 33]
])

#2. Compute total resources required 
total_resources = np.sum(ar,axis = 0)
resource_names = ['oxygen','water','food']
print(f'Total resources needed (tons): {resource_names[0]} : {total_resources[0]} {resource_names[1]} : {total_resources[1]} {resource_names[2]} : {total_resources[2]}')

#3. which resource had the highest consumption
high_consumptions = np.max(ar)
month_idx, res_idx = np.unravel_index(np.argmax(ar), ar.shape)
print(f"Highest consumption in a month: {resource_names[res_idx]} ({high_consumptions} tons in month {month_idx + 1})")

#4. standard deviation 
std_deviation = np.std(ar,axis=0)
print(f'Standard deviation of consumption:{resource_names[0]} : {np.round(std_deviation[0],1) } {resource_names[1]} : {np.round(std_deviation[1],1) } {resource_names[2]} : {np.round(std_deviation[2],1) }')

# Transpose
transposed = ar.T
print("Transposed Matrix:",transposed)

Total resources needed (tons): oxygen : 128 water : 252 food : 206
Highest consumption in a month: water (50 tons in month 4)
Standard deviation of consumption:oxygen : 4.3 water : 4.4 food : 3.2
Transposed Matrix: [[15 20 25 18 22 28]
 [40 42 38 50 37 45]
 [32 35 30 40 36 33]]


In [13]:
# 3: Basketball Performance Analyzer 

points = np.array([
    [10, 25, 30, 22, 12, 18, 26, 32, 24, 29],
    [20, 15, 12, 28, 24, 26, 30, 18, 22, 25],
    [35, 30, 32, 40, 28, 34, 29, 31, 26, 37],
    [12, 18, 20, 15, 22, 14, 19, 21, 23, 17],
    [28, 26, 27, 25, 30, 29, 35, 32, 31, 38]
])

# each player’s average points per game
avg_points = np.mean(points, axis = 1)
print(avg_points)

# 3. best and worst performing players
total_points = np.sum(points, axis=1)
best_index = np.argmax(total_points)
worst_index = np.argmin(total_points)

print(f"Best-performing player: Player {best_index + 1} (Total: {total_points[best_index]} points)")
print(f"Worst-performing player: Player {worst_index + 1} (Total: {total_points[worst_index]} points)")

#filter out games where a player scored above 30 points 
print("Games with scores above 30:")
for i in range(points.shape[0]):  # Iterate by index
    row = points[i]
    game_indices = np.where(row > 30)[0]
    if len(game_indices) > 0:
        game_list = [idx + 1 for idx in game_indices]
        print(f"Player {i + 1}: Games {game_list}")
        
# sort players in desc order

sort_p = np.argsort(-total_points)
print("Sorted Players by Total Points:")
for i in range(len(sort_p)):
    idx = sort_p[i]
    print(f"{i + 1}. Player {idx + 1} - {total_points[idx]} points")

[22.8 22.  32.2 18.1 30.1]
Best-performing player: Player 3 (Total: 322 points)
Worst-performing player: Player 4 (Total: 181 points)
Games with scores above 30:
Player 1: Games [8]
Player 3: Games [1, 3, 4, 6, 8, 10]
Player 5: Games [7, 8, 9, 10]
Sorted Players by Total Points:
1. Player 3 - 322 points
2. Player 5 - 301 points
3. Player 1 - 228 points
4. Player 2 - 220 points
5. Player 4 - 181 points
